# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c72930ee1f74fd647d9f8477807fd8268ad243a1f323eed965dbac1311f6ca148b1996a1077094ad76329eae684bbc676fe563d9c1e7109c0e5dce7de07d32d

test:
  secret_key_base: b348e88cedd48b222ae58f2ff994509e1ebf6f3e7a8e98a9862cc91f234aad7b25dbf6362a75072805ab93c88e217aa33bd2e9026bd2667566d33828236b7e18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
